name             'opusblog'
maintainer       'Andrew Brady'
maintainer_email 'bradya at robotcoffee dot com'
license          'All rights reserved'
description      'Installs/Configures opusblog'
long_description 'Installs/Configures opusblog'
version          '0.1.0'

depends 'tar', '~> 0.7.0'
depends 'mysql', '~> 6.1.2'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'database', '~> 4.0.9'
depends 'nginx', '~> 2.7.6'
depends 'hhvm', '~> 0.6'

supports 'ubuntu'
